POST https://shop-and-ship-backend.onrender.com/api/userWeb/createDashboard
Content-Type: application/json

{
  "navbar": {
    "background": "linear-gradient(to right, #2a5298, #1e3c72)",
    "textColor": "#ffffff",
    "logo": "https://example.com/logo.png",
    "device": "mobile",
    "dashboardBackground": "linear-gradient(to right, #141e30, #243b55)"
  }
}

###
POST https://shop-and-ship-backend.onrender.com/api/userWeb/updateDashboard
Content-Type: application/json

{
  "navbar": {
    "id": "649c5a8c9d4a3c9a9a9a9a9a",
    "background": "linear-gradient(to right, #2a5298, #1e3c72)",
    "textColor": "#ffffff",
    "logo": "https://example.com/logo.png",
    "device": "mobile",
    "dashboardBackground": "linear-gradient(to right, #141e30, #243b55)"
  }
}
###
GET https://shop-and-ship-backend.onrender.com/api/userWeb/getAllDashboards

###
POST https://shop-and-ship-backend.onrender.com/api/userWeb/deleteDashboard
Content-Type: application/json

{
  "id": "649c5a8c9d4a3c9a9a9a9a9a"
}