POST https://ready-backend-setup.onrender.com/api/orders/order-recive
Content-Type: application/json

{
  "orderId": "1234567890",
  "name": "John Doe",
  "phone": "1234567890",
  "address": "123 Main St",
  "pincode": "123456",
  "country": "USA",
  "state": "California",
  "city": "San Francisco",
  "weight": "1 kg"
}

###
GET https://ready-backend-setup.onrender.com/api/orders/all-orders

###
GET https://ready-backend-setup.onrender.com/api/orders/all-country-orders

###
POST https://ready-backend-setup.onrender.com/api/orders/country-order
Content-Type: application/json

{
  "countryName": "USA",
  "countryCode": "US",
  "numberOfOrders": 10,
  "status": "pending"
}

###
POST https://ready-backend-setup.onrender.com/api/orders/upload-recipt
Content-Type: application/json

{
  "id" : "68b81b611167b47b922ee2e6",
  "recipt": "image upload working"
}

###
POST https://ready-backend-setup.onrender.com/upload
Content-Type: multipart/form-data

file: <path_to_file>
###
POST https://ready-backend-setup.onrender.com/api/orders/country-orders
Content-Type: application/json

{
  "country": "India"
}

###
POST https://ready-backend-setup.onrender.com/api/orders/edit-order
Content-Type: application/json

{
  "orderId": "1234567777",
  "name": "Ganga Server",
  "phone": "1234567890",
  "address": "123 Main St",
  "pincode": "123456",
  "country": "USA",
  "state": "California",
  "city": "San Francisco",
  "weight": "1 kg",
  "orderAmount": 299
}

###
POST https://ready-backend-setup.onrender.com/api/orders/delete-order
Content-Type: application/json

{
  "orderId": "1234567890"
}