POST https://ready-backend-setup.onrender.com/api/orders/order-recive
Content-Type: application/json

{
  "orderId": "1234567890",
  "name": "John Doe",
  "barcode": "1234567890",
  "phone": "1234567890",
  "address": "123 Main St",
  "pincode": "123456",
  "country": "USA",
  "state": "California",
  "city": "San Francisco"
}

###
GET https://ready-backend-setup.onrender.com/api/orders/all-orders

###
POST https://ready-backend-setup.onrender.com/api/orders/country-order
Content-Type: application/json

{
  "countryName": "USA",
  "countryCode": "US",
  "numberOfOrders": 10,
  "status": "pending"
}

###
POST https://ready-backend-setup.onrender.com/api/orders/upload-recipt
Content-Type: application/json

{
  "id" : "68b81b611167b47b922ee2e6",
  "recipt": "image upload working"
}