POST http://localhost:4005/api/palletPacking/createPalletPacking 
Content-Type: application/json

{
    "countryName": "Somalia",
    "countryCode": "SMLA001",
    "numberOfOrders": 10,
    "numberOfBags": 2,
    "totalWeight":89,
    "airCompany":"AirIndia",
    "bagPackIdList": ["68c003328fb3cd3f3e74a97c", "68c00c208fb3cd3f3e74a995"]
}

###
GET https://ready-backend-setup.onrender.com/api/palletPacking/getAllPalletPacking
###
POST https://ready-backend-setup.onrender.com/api/palletPacking/statusUpdatePallet
Content-Type: application/json

{
    "id": "68c003328fb3cd3f3e74a97c",
    "status": "received"
}