POST https://ready-backend-setup.onrender.com/api/parcelBagPack/createBagPack
Content-Type: application/json

{
    "country":"India",
    "numberOfParcel": 10,
    "totalWeight": 28,
    
}
###
GET https://ready-backend-setup.onrender.com/api/parcelBagPack/getAllBagPack