POST https://shop-and-ship-backend.onrender.com/api/userWeb/createPaymentPartner
Content-Type: application/json

{
    "name": "Rupee Credit Card",
    "discription": "enjoy shop with card",
    "paymentImage": "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60"
}

###


POST https://shop-and-ship-backend.onrender.com/api/userWeb/updatePaymentPartner
Content-Type: application/json

{
    "id": "613b5c8c9c4c6f0c7a8b7c6d",
    "name": "ONE Credit Card",
    "discription": "This is the first home slide",
    "paymentImage": "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60"
}
###
GET https://shop-and-ship-backend.onrender.com/api/userWeb/getAllPaymentPartners

###
POST https://shop-and-ship-backend.onrender.com/api/userWeb/deletePaymentPartner
Content-Type: application/json

{
    "id": "613b5c8c9c4c6f0c7a8b7c6d"
}