POST http://localhost:4005/api/users/register-admin
Content-Type: application/json

{
    "name": "Ganga",
    "email": "gangafullstack963@gmail.com",
    "phone": "7702441016",
    "password": "ganga@123",
    "role": "africaTransitAdmin"
}
###
GET http://localhost:4005/api/users/get-all-india-admins
###

POST http://localhost:4005/api/users/admin-login
Content-Type: application/json

{
    "email": "gangafullstack963@gmail.com",
    "password": "ganga@123",
    "role": "africaTransitAdmin"
}

###

POST http://localhost:4005/api/users/register
Content-Type: application/json

{
    "name": "user",
    "email": "user@user.com",
    "password": "user"
}

###

POST http://localhost:4005/api/users/update-admins-status
Content-Type: application/json

{
    "id":"6895d29e5413053f4b4f2660",
    "status":"active",
    "role":"indiaAdmin"
}
###
POST http://localhost:4005/api/users/create-personal-user
Content-Type: application/json

{
    "name": "Ganga",
    "email": "gangafullstack963@gmail.com",
    "phone": "7702441016",
    "password": "ganga@123"
}
###
POST http://localhost:4005/api/users/login-personal-user
Content-Type: application/json

{
    "email": "gangafullstack963@gmail.com",
    "password": "ganga@123"
}