POST https://shop-and-ship-backend.onrender.com/api/users/registerAdmin
Content-Type: application/json

{
    "name": "Ganga",
    "email": "gangafullstack963@gmail.com",
    "phone": "7702441016",
    "password": "ganga@123",
    "role": "admin"
}
###
POST http://localhost:4009/api/users/adminLogin
Content-Type: application/json

{
    "email": "gangafullstack963@gmail.com",
    "password": "ganga@123"
}
###
POST https://shop-and-ship-backend.onrender.com/api/users/registerUser
Content-Type: application/json

{
    "name": "gayaz",
    "email": "gangafullstack963@gmail.com",
    "phone": "7702441019",
    "password": "12345",
    "country": "Somalia"
}
###
POST http://localhost:4009/api/users/verifyUser
Content-Type: application/json

{
    "email": "mohammed.gayaz@afri-trading.com",
    "phone": "7702441010",
    "otp": "288518"
}
###
POST https://shop-and-ship-backend.onrender.com/api/users/resendOtp
Content-Type: application/json

{
    "email": "gangafullstack963@gmail.com",
    "phone": "7702441016"
}
###
POST https://shop-and-ship-backend.onrender.com/api/users/userLogin
Content-Type: application/json

{
    "emailOrPhone": "gangafullstack963@gmail.com",
    "password": "ganga@123"
}
###
GET https://shop-and-ship-backend.onrender.com/api/users/getAllUsers

###
GET https://auto-spare-parts-backend-gbsc.onrender.com/getProducts