POST http://localhost:4009/api/users/registerAdmin
Content-Type: application/json

{
    "name": "Ganga",
    "email": "gangafullstack963@gmail.com",
    "phone": "7702441016",
    "password": "ganga@123",
    "role": "admin"
}
###
POST http://localhost:4009/api/users/adminLogin
Content-Type: application/json

{
    "email": "gangafullstack963@gmail.com",
    "password": "ganga@123"
}
###
